#include <stddef.h>

const char *mg_storage_schema_sql(void) {
  return
    "PRAGMA journal_mode = WAL;"
    "PRAGMA synchronous = NORMAL;"
    "PRAGMA foreign_keys = ON;"
    "PRAGMA mmap_size = 268435456;"
    "CREATE TABLE IF NOT EXISTS nodes ("
    "  id BLOB PRIMARY KEY,"
    "  content_hash BLOB NOT NULL UNIQUE,"
    "  summary TEXT NOT NULL,"
    "  detail TEXT NOT NULL,"
    "  created_at INTEGER NOT NULL,"
    "  last_access INTEGER NOT NULL,"
    "  access_count INTEGER NOT NULL DEFAULT 0,"
    "  state INTEGER NOT NULL DEFAULT 0"
    ");"
    "CREATE INDEX IF NOT EXISTS idx_nodes_hash ON nodes(content_hash);"
    "CREATE INDEX IF NOT EXISTS idx_nodes_state ON nodes(state);"
    "CREATE VIRTUAL TABLE IF NOT EXISTS node_fts USING fts5("
    "  summary, detail,"
    "  content='nodes', content_rowid='rowid',"
    "  tokenize='unicode61 remove_diacritics 2'"
    ");"
    "CREATE TRIGGER IF NOT EXISTS nodes_ai AFTER INSERT ON nodes BEGIN "
    "  INSERT INTO node_fts(rowid, summary, detail) VALUES (new.rowid, new.summary, new.detail);"
    "END;"
    "CREATE TRIGGER IF NOT EXISTS nodes_au AFTER UPDATE ON nodes BEGIN "
    "  INSERT INTO node_fts(node_fts, rowid, summary, detail) VALUES ('delete', old.rowid, old.summary, old.detail);"
    "  INSERT INTO node_fts(rowid, summary, detail) VALUES (new.rowid, new.summary, new.detail);"
    "END;"
    "CREATE TRIGGER IF NOT EXISTS nodes_ad AFTER DELETE ON nodes BEGIN "
    "  INSERT INTO node_fts(node_fts, rowid, summary, detail) VALUES ('delete', old.rowid, old.summary, old.detail);"
    "END;"
    "CREATE TABLE IF NOT EXISTS keywords ("
    "  id INTEGER PRIMARY KEY AUTOINCREMENT,"
    "  text TEXT NOT NULL UNIQUE COLLATE NOCASE,"
    "  canonical_id INTEGER REFERENCES keywords(id),"
    "  embedding BLOB"
    ");"
    "CREATE TABLE IF NOT EXISTS node_keywords ("
    "  node_id BLOB NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,"
    "  keyword_id INTEGER NOT NULL REFERENCES keywords(id),"
    "  PRIMARY KEY (node_id, keyword_id)"
    ");"
    "CREATE INDEX IF NOT EXISTS idx_nk_kw ON node_keywords(keyword_id);"
    "CREATE TABLE IF NOT EXISTS edges ("
    "  src BLOB NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,"
    "  dst BLOB NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,"
    "  kind INTEGER NOT NULL,"
    "  keyword_id INTEGER,"
    "  weight REAL NOT NULL"
    ");"
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_edges_unique ON edges(src, dst, kind, COALESCE(keyword_id, -1));"
    "CREATE INDEX IF NOT EXISTS idx_edges_src ON edges(src, kind);"
    "CREATE INDEX IF NOT EXISTS idx_edges_dst ON edges(dst, kind);"
    "CREATE TABLE IF NOT EXISTS similarity_samples ("
    "  ts INTEGER NOT NULL,"
    "  kind INTEGER NOT NULL,"
    "  cosine REAL NOT NULL"
    ");"
    "CREATE INDEX IF NOT EXISTS idx_samples_kind ON similarity_samples(kind);";
}
